### Get All Tasks
GET http://localhost:3000/task HTTP/1.1;

### Get Task by Id
GET http://localhost:3000/task/674533607fe7a981880bda10 HTTP/1.1

### Create Task 
POST http://localhost:3000/task
content-type: application/json

{
    "title": "Complete Final Project",
    "description": "I need to complete the final project and get a passing grade",
    "dueDate": "12-4-2024",
    "status": "active",
    "priority": "High",
    "userId":"WIP",
    "tags":"School, Homework, Project",
    "categoryId":"WIP"
}
### Update Task
PUT http://localhost:3000/task/674533607fe7a981880bda10 HTTP/1.1
Content-Type: application/json

{
    "title": "Complete Final Project",
    "description": "I need to complete the final project and get a passing grade",
    "dueDate": "12-4-2024",
    "status": "active",
    "priority": "High",
    "userId":"WIP",
    "tags":"School, Homework, Project",
    "categoryId":"WIP"
}
### Delete Task
DELETE http://localhost:3000/task/1454323432123 HTTP/1.1